export default class Constants {
  static readonly WIDTH_100: string = '100%';
  static readonly WIDTH_40: string = '40%';
  static readonly WIDTH_75: string = '75%';
  static readonly WIDTH_23: string = '23%';
  static readonly PADDING_20: string = '20vp';
  static readonly MARGIN_15: string = '15vp';
  static readonly MARGIN_30: string = '30vp';
  static readonly TEXT_SIZE_20: string = '20fp';
  static readonly TEXT_SIZE_60: string = '60fp';
  static readonly RADIO_30: string = '30vp';
}